language: node_js
node_js:
  - 6

before_script:
  - npm install -g bower
  - bower install
  - git clone -b development https://github.com/json-schema-form/json-schema-form-core.git ../json-schema-form-core

sudo: false
